name: aurora_gallery
description: Aurora — быстрая, плотная и стильная галерея с настраиваемыми темами.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  file_picker: ^8.0.0
  shared_preferences: ^2.2.0
  http: ^1.2.0
  path: ^1.9.0

dev_dependencies:
  flutter_li